/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SetWallpaperNative */

#ifndef _Included_SetWallpaperNative
#define _Included_SetWallpaperNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SetWallpaperNative
 * Method:    setWallpaper
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_SetWallpaperNative_setWallpaper
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
